package de.kumpelblase2.dragonslair.api;

public enum TriggerType
{
	BLOCK_PLACE,
	NPC_INTERACT,
	MOVEMENT,
	BLOCK_BREAK,
	NPC_TOUCH,
	DIALOG_OCCUR,
	BLOCK_INTERACT,
	CHAPTER_CHANGE,
	OBJECTIVE_CHANGE,
	NPC_DAMAGE,
	GATHER_ITEM,
	MOBS_KILLED,
	NPC_DEATH,
	LEVEL_ACHIEVE,
	ITEM_CRAFT
}